# Generated by Django 2.1.2 on 2018-11-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addre', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('amphur', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactType', models.CharField(choices=[('Home', 'บ้าน'), ('Work', 'ที่ทำงาน'), ('Mobile', 'มือถือ'), ('Mobile2', 'มือถือ2')], max_length=100)),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='education_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_grade', models.CharField(max_length=200, null=True)),
                ('edu_degree', models.CharField(blank=True, max_length=200, null=True)),
                ('edu_major', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='org_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_address', models.CharField(max_length=255)),
                ('org_website', models.URLField(blank=True, null=True)),
                ('org_tel', models.CharField(blank=True, max_length=255, null=True)),
                ('org_field', models.CharField(blank=True, max_length=255, null=True)),
                ('org_mail', models.EmailField(blank=True, max_length=255, null=True)),
                ('org_fund', models.CharField(blank=True, max_length=255, null=True)),
                ('org_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.org_categories')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('mr', 'นาย'), ('mrs', 'นาง'), ('ms', 'นางสาว'), ('dr', 'ดร.'), ('Asst', 'ผศ.'), ('Asst Dr', 'ผศ. ดร.'), ('ML', 'มล.')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('sex_status', models.CharField(choices=[('male', 'ผู้ชาย'), ('female', 'ผู้หญิง')], max_length=255)),
                ('status', models.CharField(choices=[('single', 'โสด'), ('married', 'แต่งงาน'), ('divorce', 'หย่าร้าง'), ('complicated', 'ซับซ้อน')], max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('mobiles', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('latCo', models.CharField(blank=True, max_length=255, null=True)),
                ('longCo', models.CharField(blank=True, max_length=255, null=True)),
                ('relation', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.address')),
                ('friends', models.ManyToManyField(blank=True, related_name='_person_friends_+', to='persons.person')),
            ],
        ),
        migrations.CreateModel(
            name='religions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=255)),
                ('sect', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.religions'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AddField(
            model_name='education',
            name='edu_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.education_grade'),
        ),
        migrations.AddField(
            model_name='education',
            name='edu_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='persons.person'),
        ),
        migrations.AddField(
            model_name='contact',
            name='personContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
    ]
