# Generated by Django 2.1.2 on 2018-11-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='_person_friends_+', to='persons.person'),
        ),
    ]
