# Generated by Django 2.1.2 on 2018-11-28 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='addre',
        ),
        migrations.RemoveField(
            model_name='person',
            name='edu_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='person',
            name='personCoordinate',
        ),
        migrations.AddField(
            model_name='address',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AddField(
            model_name='education',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AddField(
            model_name='facebookacc',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AddField(
            model_name='instagramacc',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AddField(
            model_name='personcoor',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AddField(
            model_name='twitteracc',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
        migrations.AlterField(
            model_name='facebookacc',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instagramacc',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twitteracc',
            name='twitter',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
