# Generated by Django 2.1.2 on 2018-11-16 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addre', models.CharField(max_length=255, null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('amphur', models.CharField(max_length=255, null=True)),
                ('province', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='Srelation',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='_person_friends_+', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='education_grade',
            name='edu_grade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education_grade',
            name='edu_major',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_field',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_fund',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_mail',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_tel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='edu_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.education'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='instagram',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='latCo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='longCo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobiles',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='organization_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='relation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='religion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.religions'),
        ),
        migrations.AlterField(
            model_name='person',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('single', 'โสด'), ('married', 'แต่งงาน'), ('divorce', 'หย่าร้าง'), ('complicated', 'ซับซ้อน')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('mr', 'นาย'), ('mrs', 'นาง'), ('ms', 'นางสาว')], max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='religions',
            name='sect',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='addre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.address'),
        ),
    ]
