# Generated by Django 2.1.2 on 2018-11-26 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20181124_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='personCoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='latCo',
        ),
        migrations.RemoveField(
            model_name='person',
            name='longCo',
        ),
        migrations.AddField(
            model_name='personcoor',
            name='latitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latitude_person', to='persons.person'),
        ),
        migrations.AddField(
            model_name='personcoor',
            name='longtitude',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='longtitude_person', to='persons.person'),
        ),
    ]
