# Generated by Django 2.1.2 on 2018-11-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20181121_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='organization_name',
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='persons.person'),
        ),
    ]
